name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter_launcher_icons:
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true
